### PR TITLE
natrium: move stuff to vendor

### PR DESCRIPTION
**Pull request by wegank**

### CODE REVIEW

**Comment by MZO9400** [comment]
Thanks! Did you try? Are you sure it doesn't need anything else: any hex editing or something alike?

**Comment by wegank** [comment]
I've compiled LineageOS with Treble enabled and SELinux set to permissive. No extra hex editing needed.

**Comment by MZO9400** [comment]
You don't know if it is Treble compatible till you are able to boot GSI. Try Phh-Treble

**Comment by wegank** [comment]
You're right, it's just false positive as Phh-Treble build won't boot (with/without this commit). May take some time for me to figure it out, before that this pull request is now closed.

**Comment by wegank** [comment]
Found I've just messed up with SELinux policy. Everything works on Phh-Treble except that SELinux's permissive, still, no extra hex editing needed.
[Screenshot](https://imgur.com/a/NIcmj)

**Comment by MZO9400** [comment]
Ah. Awesome!

**Pull request merged**
